name: Controllo Clima Sala Riunioni

on:
  # schedule:
  #   - cron: '*/10 8-18 * * 1-5' # ogni 10 minuti, dalle 8 alle 18, lun-ven
  workflow_dispatch: # permette anche di far partire manualmente il workflow

jobs:
  accendi-clima:
    runs-on: ubuntu-latest
    steps:
      - name: Accendi clima
        run: |
          curl -X POST "${{ secrets.REPLIT_URL }}" \
          -H "Content-Type: application/json" \
          -d "{\"action\": \"start\", \"token\": \"${{ secrets.REPLIT_TOKEN }}\"}"

  spegni-clima:
    runs-on: ubuntu-latest
    steps:
      - name: Spegni clima
        run: |
          curl -X POST "${{ secrets.REPLIT_URL }}" \
          -H "Content-Type: application/json" \
          -d "{\"action\": \"stop\", \"token\": \"${{ secrets.REPLIT_TOKEN }}\"}"
