name: Controllo Clima Sala Riunioni

on:
  schedule:
    - cron: '*/10 6-16 * * 1-5'  # ogni 10 minuti dalle 8 alle 18 ora italiana, lun-ven
  workflow_dispatch:  # per trigger manuale

jobs:
  controllo-clima:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Installa dipendenze
        run: |
          pip install msal requests python-dateutil

      - name: Esegui script controllo clima
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          REPLIT_URL: ${{ secrets.REPLIT_URL }}
          REPLIT_URL_STATE: ${{ secrets.REPLIT_URL_STATE }}    # <-- aggiunto qui
          REPLIT_TOKEN: ${{ secrets.REPLIT_TOKEN }}
        run: |
          python control_climate.py
