name: Ping Replit Apps per mantenerle attive

on:
  schedule:
    - cron: '*/10 * * * *'  # ogni 10 minuti
  workflow_dispatch:

jobs:
  ping-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Ping app REPLIT_URL
        run: curl -fsSL ${{ secrets.REPLIT_URL }} || echo "Ping REPLIT_URL fallito"

      - name: Ping app REPLIT_URL_STATE
        run: curl -fsSL ${{ secrets.REPLIT_URL_STATE }} || echo "Ping REPLIT_URL_STATE fallito"
