name: Test Accendi Clima

on:
  workflow_dispatch:

jobs:
  accendi-clima:
    runs-on: ubuntu-latest
    steps:
      - name: Accendi clima
        run: |
          curl -X POST "https://38ebb343-e06e-485b-8279-df66a907e5e2-00-tytogezsfnhn.picard.replit.dev/clima" -d '{"action": "start"}' -H "Content-Type: application/json"
